config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'

  root 'main#dashboard'

  
  devise_for :users,
  	controllers: { sessions: 'user/sessions', registrations: 'user/registrations' },
    path_names: { sign_in: "login/main", sign_out: "logout", sign_up: "register/:type" }
    
  resources :users
  resources :tags
  
  resources :questions do
  	resources :answers
  	resources :tags
  end
    
  resources :clients do
  	resources :questions
  	resources :followers
  end
    
  
  match '/login' => "main#login", via: [:get, :post]
  match '/login/start' => "users#login", via: [:post]
  match '/logout' => "users#logout", via: [:get, :post]
  match '/dashboard' => "main#dashboard", via: [:get, :post]
end

app/models/question.rb
class Question < ActiveRecord::Base
	ratyrate_rateable "vote"
	
	belongs_to :client
	has_many :answers, :dependent => :destroy
	has_and_belongs_to_many :tags, class_name: "Tag"
	
	accepts_nested_attributes_for :answers
	
	attr_accessor :tag_list
	
	after_find :set_tag_list 
	after_initialize :set_tag_list
	
	scope :paginable, ->(page, limit){ paginate(:page => page, :per_page => limit) }		
	scope :recents, ->(page, limit){ includes(:client).order(updated_at: :desc).paginable(page, limit) }
	scope :client_recents, ->(client, page, limit){ by_client(client).recents(page, limit) }
	scope :by_client, ->(client){ includes(:client).where(client: client) }
	scope :find_by_id, ->(id){ find_by id: id }
	scope :last_questions_for_client, ->(client, page, limit){ includes(:answers).where(answers: {client: client}).paginable(page, limit).order('answers.updated_at, answers.created_at')  }
	
	#METODOS PROPIOS DE LA CLASE
	def createdAtFormated
		dateFormat created_at
	end
	
	def updatedAtFormated
		dateFormat updated_at
	end
	
	def save_or_update(params)
		registration = new_registration(params)
		registration.save_or_update
	end
	
	def update_visits_count
		registration = new_registration({visits_count: self.visits_count+=1 })
		registration.save_or_update
	end
	
	def validate_tag(tag_param)
		self.tags.any?{|tag| tag.description.downcase == tag_param.downcase }
	end
	
	def tag_list_split(&proc)
		self.tag_list.split(",").each { |tag| proc.call(tag) } #if !self.tag_list.nil?
	end
		
private
	def dateFormat(date)
		date.strftime "%d-%m-%Y a las %H:%M"
	end
	
	def new_registration(params)
		QuestionRegistration.new(self, params)
	end
	
	def set_tag_list
		if self.tag_list.nil?
			self.tag_list = ""
			self.tags.each { |tag| self.tag_list += "#{tag.description}, " }
		end
	end
	
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  
  respond_to :html, :json
  
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
  	@params = {
  		:actions => false
  	}
    page = (params["page"] != nil) ? params["page"] : 1
    if params["client_id"] != nil
    	@params[:actions] = true
    	@params[:div] = "me-question-list"
    	@params[:title] = "Mis Preguntas"
    	@questions = Question.client_recents(Client.find_by_id(params["client_id"]), page, PAGE_SIZE)
    else
    	@params[:div] = "question-list-recent"
    	@params[:title] = "Preguntas Recientes"
    	@questions = Question.recents(page, PAGE_SIZE)
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  	@client_decorator = ClientDecorator.new(current_user, @question.client)
  	@question.update_visits_count if !@client_decorator.same_client?
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new
    @question.client = current_user.client
    
	if @question.save_or_update(question_params)
		respond_with @question
	else
		respond_using @question, :new
	end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
  	if @question.save_or_update(question_params)
		respond_with @question
	else
		respond_using @question, :edit
	end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_destroy questions_url, "La pregunta"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :description, :tag_list)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render "layouts/form/texfield", f: f, input: {id: :title, label: "Titulo"} %>
  
  <%= render "layouts/form/texfield", f: f, input: {id: :description, type: "textarea", label: "Descripcion"} %>
 
  <!-- TAGS -->
  <%= render "layouts/form/texfield", f: f, input: {id: :tag_list, label: "Tags" } %>
  
 
  <!-- BUTTONS -->
  <div class="mdl-card__actions mdl-card--border">
  	<div class="actions">
    	<%= render "layouts/buttons", f: f %>
  	</div>
  </div>
<% end %>

app/views/questions/_info_client.html.erb
<hr />
<div class="row">
		<div class="col s6 left-align info_client">
			Ultima actualización: <%= question.updatedAtFormated %><br/>
			Vista: <%= question.visits_count %>
		</div>
		<div class="col s6">
			<div class="card-panel teal lighten-5 info_client">
				Pregunta realizada por <%= link_to question.client.fullName, client_path(question.client) %> 
				el dia <%= question.createdAtFormated %>
			</div>
		</div>
</div>

app/views/questions/_question_fields_list.html.erb
<% if actions %>
	<%= link_to 'Nueva Pregunta', new_question_path %>
<% end %>

<ul class="collection">
	<% questions.each do |question| %>
		<li class="collection-item avatar">
    		<span class="title"><%= question.title %></span>
    		<span class="hide-on-small-only count">
    			Respuestas: <span class="blue-text text-darken-4"><%= question.answers.count %></span><br/>
    			Vista: <span class="blue-text text-darken-4"><%= question.visits_count %></span>
    		</span>
    		<blockquote>
    			realizada por <%= link_to question.client.fullName, client_path(question.client) %> 
				el dia <%= question.createdAtFormated %>
			</blockquotep>
    		<div class="secondary-content">
    			<!-- <a href="#!"><i class="material-icons">grade</i></a><br/> -->
    			<a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Ver Pregunta"
    				href="<%= question_path question %>">
    				<i class="material-icons">send</i>
    			</a>
    		</div>
    	</li> 
    	<!-- <td><%= link_to 'Show', question %></td> 
        <td><%= link_to 'Edit', edit_question_path(question) %></td> -->  
	<% end %>
	<%= render "/layouts/form/paginable", colspan: 2, paginable: @questions, div: div %>
</ul>

app/views/questions/edit.html.erb
<%= render 'layouts/header' %>

<div class="container">
	<%= render "layouts/card/top", card: {class: "col l10 offset-l1"} %>
		<div class="card-content">
			<%= render "layouts/form/title", title: "Editar Pregunta" %>
			<div class="mdl-card__supporting-text mdl-card__actions mdl-card--border">
				<%= render 'form' %>
			</div>
		</div>
	<%= render "layouts/card/bottom" %>
	<%= link_to 'Regresar', question_path(@question) %>
</div>

<%= render 'layouts/footer' %> 

app/views/questions/index.html.erb
<div id="<%= @params[:div] %>">
	<h3 class="header"><%= @params[:title] %></h3>
	<%= render "question_fields_list", div: @params[:div], questions: @questions, actions: @params[:actions] %>
</div>
<!-- <br>
<%= link_to 'New Question', new_question_path %> -->

app/views/questions/new.html.erb
<%= render 'layouts/header' %>

<div class="container">
	<%= render "layouts/card/top", card: {class: "col l10 offset-l1"} %>
		<div class="card-content">
			<%= render "layouts/form/title", title: "Nueva Pregunta" %>
			<div class="mdl-card__supporting-text mdl-card__actions mdl-card--border">
				<%= render 'form' %>
			</div>			
		</div>
	<%= render "layouts/card/bottom" %>
	<%= link_to 'Back', "/dashboard" %>
</div>

<%= render 'layouts/footer' %> 

app/views/questions/show.html.erb
<%= render 'layouts/header' %>

<!-- <p id="notice"><%= notice %></p> -->

<div class="row">
  	<div class="col s12 m6 l6">
  	
		<%= render "layouts/card/top", card: {class: ""} %>
			<div class="card-content">
				<%= render "layouts/form/title", title: @question.title %>
				
				<div class="content_supporting-text">
					<div class="col s3 m3 l3 raiting">
						<% if @question.rates('vote').count > 0 %>
							<%= rating_for @question, "vote", imdb_avg: true %>
						<% end %>
						<% if !@client_decorator.same_client? and @client_decorator.current_user? %>
							<p>Mi Clasificaci&oacute;n:</p>
							<%= rating_for @question, "vote" %>
						<% end %>
					</div>
					
					<div class="col s9 m9 l9 text"><%= @question.description %></div>
					<div class="tags">
						<% @question.tags.each do |tag| %>
							<div class="chip">
								<% if !@user.nil? and @user.client == @question.client %>
									<i id="<%= question_tag_path(@question, tag, format: :json) %>" 
									class="material-icons">close</i>
								<% end %>
								<%= tag.description %>
							</div>
						<% end %>
					</div>
					<%= render "questions/info_client", question: @question %>
					
				</div>
	
				<% if (!@user.nil? and @question.client.id == @user.client.id) %>
					 <div class="actions card-action left-align">
  						<%= link_to 'Editar', edit_question_path(@question) %>
  						<%= link_to 'Regresar', "/dashboard" %>
  					</div>
  				<% elsif(!@user.nil?) %>
  					<div class="actions card-action left-align">
  						<%= link_to 'Responder', 'javascript:respond()' %>
  					</div>
  				<% elsif(!@user.nil?) %>
  					<div class="actions card-action left-align">
  						<%= link_to 'Responder', 'javascript:respond()' %>
  					</div>
  				<% end %>
  			
  			</div>
		<%= render "layouts/card/bottom" %>
		
		<div id="respond"></div>
				
	</div>
	
	<div class="col s12 m6 l6">
		<div id="answers"></div>
	</div>
	
</div>

<script>
	function respond(){		
		$("#respond").load("<%= new_question_answer_path (@question) %>?ajax=true");
	}
	
	$(document).ready(function() {
		$("#answers").load("<%= question_answers_path (@question) %>?ajax=true");
		$(".chip > i").on('click', function(e){
			console.log(e.target.id);
			$.ajax({
    			url: e.target.id,
        		type: 'DELETE',
        		error: function(result, textStatus, serverEstatus){
        			console.log(result.responseText);
            		console.log(textStatus);
            		console.log(serverEstatus);
        		}
  			});
		});
	});
</script>