config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'

  root 'main#dashboard'

  
  devise_for :users,
  	controllers: { sessions: 'user/sessions', registrations: 'user/registrations' },
    path_names: { sign_in: "login/main", sign_out: "logout", sign_up: "register/:type" }
    
  resources :users
  resources :tags
  
  resources :questions do
  	resources :answers
  	resources :tags
  end
    
  resources :clients do
  	resources :questions
  	resources :followers
  end
    
  
  match '/login' => "main#login", via: [:get, :post]
  match '/login/start' => "users#login", via: [:post]
  match '/logout' => "users#logout", via: [:get, :post]
  match '/dashboard' => "main#dashboard", via: [:get, :post]
end

app/models/client.rb
class Client < ActiveRecord::Base
	ratyrate_rater
	
	enum sex: ["Masculino", "Femenino"]
	
	has_many :users, :dependent => :destroy
	has_many :questions, :dependent => :destroy
	has_many :answers, :dependent => :destroy
	has_many :followers, :dependent => :destroy
	
	accepts_nested_attributes_for :users, :questions, :answers
	
	validates_presence_of :first_name, :first_last_name, :sex, :age
	validates_numericality_of :age
	
	validates_associated :users
	
	scope :find_by_id, ->(id){ find_by id: id }
	
	#METODOS PROPIOS DE LA CLASE
	def fullName
		"#{first_name} #{first_last_name}"
	end
	
	def currentUser
		self.users.first
	end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  
  respond_to :html, :json

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  	@client_decorator = ClientDecorator.new(current_user, @client)
  end

  # GET /clients/new
  def new
    @client = Client.new
    newUser(true)
  end

  # GET /clients/1/edit
  def edit
  	newUser(false)
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
	
	if @client.save
		respond_with (@client) do |format|
			format.html { redirect_to checkURL, notice: 'Client was successfully created.' }
		end
	else
		respond_using @client, :new
	end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
  	if @client.update(client_params)
  		respond_with (@client)
  	else
  		respond_using @client, :edit
	end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_destroy clients_url, "El Cliente"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:id, :first_name, :first_last_name, :sex, :age, users_attributes: [:id, :username, :password, :password_confirmation])
    end
    
    def newUser(create)
    	@client.users = User.actives(@client)
    	if @client.users.empty? and create
    		@client.users.build
    	end
    end
    
    def checkURL
    	(defined? params[:client][:url]) ? params[:client][:url] : @client
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client_fields.html.erb
<!-- FIRST NAME -->
<%= render "layouts/form/texfield", f: f, input: {id: :first_name, label: "Primer Nombre"} %>
  
<!-- LAST FIRST NAME -->
<%= render "layouts/form/texfield", f: f, input: {id: :first_last_name, label: "Primer Apellido"} %>

<!-- AGE -->
<%= render "layouts/form/texfield", f: f, input: {id: :age, label: "Edad", pattern: {value: "-?[0-9]*(\.[0-9]+)?"}} %>
  
<!-- SEX -->
<%= render "layouts/form/select", f: f, input: {id: :sex, label: "Genero"}, options: Client.sexes.keys.to_a %>

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if defined? url %>
  	<%= f.hidden_field "url", value: url %>
  <% end %>

  <div class="row">
  	<div class="col s12 m6 l6">
  		<div class="section">
  			<%= render "layouts/form/subtitle", subtitle: "Informacion Basica" %>
  			<%= render "clients/client_fields", :f => f %>
  		</div>
  	</div>
  	
  	<div class="col s12 m6 l6">
  		<!-- USER'S ACCES -->
  		<div class="section">
  			<%= render "layouts/form/subtitle", subtitle: "Datos de Acceso" %>
  			<%= f.fields_for :users do |user| %> 
  				<%= render "users/user_fields", :f => user %>
  			<% end %>
  		</div>
  	</div>
  </div>
  
  <!-- BUTTONS -->
  <div class="mdl-card__actions mdl-card--border">
  	<div class="actions">
    	<%= render "layouts/buttons", f: f %>
  	</div>
  </div>
<% end %>

app/views/clients/edit.html.erb
<%= render 'layouts/header' %>

<div class="container">
	<%= render "layouts/card/top", card: {class: ""} %>
		<div class="card-content">
		
			<%= render "layouts/form/title", title: "Editar Perfil" %>
	
			<div class="mdl-card__supporting-text mdl-card__actions mdl-card--border">
				<%= render 'form' %>
			</div>
			
		</div>
	<%= render "layouts/card/bottom" %>
</div>

<!--
<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>
-->

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastfirstname</th>
      <th>Sex</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.first_last_name %></td>
        <td><%= client.sex %></td>
        <td><%= client.age %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<%= render 'layouts/header' %>

<div class="container">
	<%= render "layouts/card/top", card: {class: ""} %>
		<div class="card-content">
			<%= render "layouts/form/title", title: "Nuevo Cliente" %>
  	
  			<div class="mdl-card__supporting-text mdl-card__actions mdl-card--border">
				<%= render 'form', url: "/login" %>
			</div>
			<!-- <%= link_to 'Back', clients_path, class: "link" %> -->
		</div>
	<%= render "layouts/card/bottom" %>
</div>

<%= render 'layouts/footer' %>

app/views/clients/show.html.erb
<%= render 'layouts/header' %>

<!-- <p id="notice"><%= notice %></p> -->

<div class="container">
	<%= render "layouts/card/top", card: {class: "col s12 m8 l8 offset-m2 offset-l2"} %>
		<div class="card-content">
		
			<%= render "layouts/form/title", title: @client_decorator.same_client? ? "Perfil" : "Usuario: #{@client.fullName}" %>
			<div class="mdl-card__supporting-text mdl-card__actions mdl-card--border">
				<br/>
				<div class="mdl-grid">
  					<div class="col s6">
  						<%= render "layouts/form/subtitle", subtitle: "Informacion Basica" %>
  						<%= render "layouts/form/showField", field: {name: "Nombre", value:@client.fullName} %>
						<%= render "layouts/form/showField", field: {name: "Sexo", value:@client.sex} %>
						<%= render "layouts/form/showField", field: {name: "Edad", value:@client.age} %>
					</div>
				</div>
		
				
				<div class="row">
  					<div class="col s6">
  						<% if @client_decorator.same_client? %>
  							<%= render "layouts/form/subtitle", subtitle: "Datos de Acceso" %>
							<%= render "layouts/form/showField", field: {name: "Usuario", value:@client.currentUser.username} %>
							<%= render "layouts/form/showField", field: {name: "Correo", value:@client.currentUser.email} %>
						<% end %>
					</div>
				</div>
				
				
				<div class="actions card-action left-align">
					<% if @client_decorator.same_client? %>
  						<%= link_to 'Editar', edit_client_path(@client) %>
  					<% else %>
  						<% if !@client_decorator.client_follower? and @client_decorator.current_user? %>
  							<%= link_to 'Seguir', client_followers_url(@client, format: :json), method: :post, remote: true,
  								data: { params: { follower: {client_follower_id: @client.id} } } %>
  						<% end %>
  						
  						<div id="status" class="<%= @client_decorator.client_follower? ? "" : "hide" %>">
							<p class="cyan-text text-lighten-1"><i>Siguiendo</i></p>
						</div>
  						
  					<% end %>
  					
				</div>			
			</div>
			
		</div>
	<%= render "layouts/card/bottom" %>
</div>

<%= render 'layouts/footer' %>

<script>
	$(document).ready(function() {
		$("a[data-remote]").on('ajax:success', function(e, data, status, xhr){
			$(e.target).addClass("hide");
			$("#status").removeClass("hide");
		});
	});
</script>