config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'

  root 'main#dashboard'

  
  devise_for :users,
  	controllers: { sessions: 'user/sessions', registrations: 'user/registrations' },
    path_names: { sign_in: "login/main", sign_out: "logout", sign_up: "register/:type" }
    
  resources :users
  resources :tags
  
  resources :questions do
  	resources :answers
  	resources :tags
  end
    
  resources :clients do
  	resources :questions
  	resources :followers
  end
    
  
  match '/login' => "main#login", via: [:get, :post]
  match '/login/start' => "users#login", via: [:post]
  match '/logout' => "users#logout", via: [:get, :post]
  match '/dashboard' => "main#dashboard", via: [:get, :post]
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	ratyrate_rateable "vote"
	
	belongs_to :client
	belongs_to :question
	
	scope :paginable, ->(page, limit){ paginate(:page => page, :per_page => limit) }
	scope :by_question, ->(question){ includes(:client).where(question: question) }
	
	#METODOS PROPIOS DE LA CLASE
	def createdAtFormated
		dateFormat created_at
	end
	
	def updatedAtFormated
		dateFormat updated_at
	end
	
private
	def dateFormat(date)
		date.strftime "%d-%m-%Y a las %H:%M"
	end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  respond_to :html, :json
  
  before_action :load_question
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /questions/1/answers
  # GET /questions/1/answers.json
  def index
    #@answers = Answer.all
    page = (params["page"] != nil) ? params["page"] : 1
    @answers = Answer.by_question(@question).paginable(page, PAGE_SIZE)
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  	@client_decorator = ClientDecorator.new(@user, @answer.client)
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)
    @answer.client = @user.client
    @answer.question = @question
	
	if @answer.save
		respond_with @question
	else
		respond_using @answer, :new
	end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    if @answer.update(answer_params)
    	respond_with @question, @answer
    else
    	respond_using @answer, :edit
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to @question
  end

  private
    def load_question
    	@question = Question.find_by_id(params["question_id"])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:title, :description)
    end
    
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer_fields_list.html.erb
<ul class="collection collapsible" data-collapsible="expandable">
	<% answers.each do |answer| %>
		<li id="<%= answer.id %>">
      		<div class="collapsible-header">
      			<i class="material-icons">add_circle_outline</i>
      			<%= answer.title %>
      			<% if (@user != nil and @user.client.id == answer.client.id) %>
      				<%= link_to "Editar", edit_question_answer_path(@question, answer), class: "secondary-content" %>
      			<% end %>
      		</div>
      		<div class="collapsible-body">
      			<div class="col s9 m9 l9 text"><p class="truncate"><%= answer.description %></p></div>
      			<div class="col s3 m3 l3 raiting">
					<% if answer.rates('vote').count > 0 %>
						<%= rating_for answer, "vote", imdb_avg: true %>
					<% end %>
				</div>
      			<p><%= render "answers/info_client", answer: answer %></p>
      			<hr style="width:90%"/>
      			<p>
      				<%= link_to "Ver Respuesta", question_answer_path(@question, answer) %>
      			</p>
      		</div>
    	</li>
	<% end %>
	<%= render "/layouts/form/paginable", colspan: 3, paginable: answers, div: div %>
</ul>

<script>
	$(document).ready(function(){
    	$('.collapsible').collapsible({
      		accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
    	});
  	});
</script>

app/views/answers/_form.html.erb
<%= form_for ([@question, @answer]) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
  <%= render "layouts/form/texfield", f: f, input: {id: :title, label: "Titulo"} %>
  
  <%= render "layouts/form/texfield", f: f, input: {id: :description, type: "textarea", label: "Descripcion"} %>
  
  <!-- BUTTONS -->
  <div class="mdl-card__actions mdl-card--border">
  	<div class="actions">
    	<%= render "layouts/buttons", f: f %>
  	</div>
  </div>
<% end %>

app/views/answers/_info_client.html.erb
<span class="info_client">
	Respuesta realizada por <%= link_to answer.client.fullName, client_path(answer.client) %>
	el dia <%= answer.createdAtFormated %>
</span>

app/views/answers/edit.html.erb
<%= render 'layouts/header' %>

<div class ="container">
	<%= render "layouts/card/top", card: {class: "col l10 offset-l1"} %>
		<div class="card-content">
			<%= render "layouts/form/title", title: "Editar Respuesta" %>
			<div class="mdl-card__supporting-text mdl-card__actions mdl-card--border">
				<%= render 'form' %>
			</div>
		</div>
	<%= render "layouts/card/bottom" %>

	<%= link_to 'Regresar', question_path(@question) %>
</div>

<%= render 'layouts/footer' %> 

app/views/answers/index.html.erb
<div id="answer-list">
	<%= render "answer_fields_list", div: "answer-list", answers: @answers, user: @user %>
</div>

app/views/answers/new.html.erb
<%= render "layouts/card/top", card: {class: ""} %>
	<div class="card-content">
		<%= render "layouts/form/title", title: "Nueva Respuesta" %>
		<div class="mdl-card__supporting-text mdl-card__actions mdl-card--border">
			<%= render 'form' %>
		</div>
	</div>
<%= render "layouts/card/bottom" %>

app/views/answers/show.html.erb
<%= render 'layouts/header' %>

<!--<p id="notice"><%= notice %></p>-->

<div class="container">
	<%= render "layouts/card/top", card: {class: "col s12 m8 l8 offset-m2 offset-l2"} %>
		<div class="card-content">
			<%= render "layouts/form/title", title: @answer.title %>
			<div class="content_supporting-text">
				<div class="text"><%= @answer.description %></div>
				<hr/>
				<% if !@client_decorator.same_client? and @client_decorator.current_user? %>
					<div class="raiting-me">
						<span>Mi Clasificaci&oacute;n:</span>
						<%= rating_for @answer, "vote" %>
					</div>
				<% end %>
				<div class="left-align"><%= render "answers/info_client", answer: @answer %></div>
			</div>
			<% if (!@user.nil? and @answer.client.id == @user.client.id) %>
				<div class="actions card-action left-align">
  					<%= link_to 'Editar', edit_question_answer_path(@question, @answer) %>
					<%= link_to 'Regresar', question_path(@question) %>
  				</div>
  			<% end %>
		</div>
	<%= render "layouts/card/bottom" %>
	<!--<%= link_to 'Back', question_path(@question) %>-->
</div>

<%= render 'layouts/footer' %>